### ISSUE TITLE
swap to using pip install of desc-bpz

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_bpz#4]
I just reorganized DESC_BPZ and put it on PyPI as `desc-bpz`, we should update this package to grab from there rather than GitHub

**Comment by johannct** [comment]
do we want to do that for all the external packages that I saw being created recently? If yes it might be good to post a strawman's guide to doing it quickly for developers (though I know that it is really not hard to get a package on pypi)?

**Comment by sschmidt23** [comment]
I only did this because no version of BPZ was available on PyPI and I got the go-ahead to put DESC_BPZ up from Dan Coe.  When doing so I noticed that the structure I had was copying AB, FILTER, and SED directories with package_data ("default" filters and SEDs that are supposed to ship with BPZ) to the site-packages directory upon install, so I reorganized.  
While it would be nice to clean up a few of the other packages, I don't think it's a super high priority.
